spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform_db?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      schema-locations: classpath:db/mysql/schema.sql
      data-locations: classpath:db/mysql/data.sql
